from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Staff)
admin.site.register(Course)
admin.site.register(Batch)
admin.site.register(Email)
admin.site.register(Reporting)
admin.site.register(ChatRoom)
admin.site.register(ChatMessage)
admin.site.register(Lead)
admin.site.register(Student)
admin.site.register(StudentCourseData)
admin.site.register(Job)
admin.site.register(TempBatch)
admin.site.register(StudentPaymentData)
admin.site.register(StudentPayments)
admin.site.register(Notification)
admin.site.register(Webinar)
admin.site.register(DefaultPics)
admin.site.register(BatchData)
admin.site.register(Assignment)
admin.site.register(Project)
admin.site.register(StudentAssignmentData)
admin.site.register(StudentProjectData)
admin.site.register(ChatQuery)
