# Generated by Django 3.2.8 on 2021-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/dp/'),
        ),
    ]
