# Generated by Django 3.2.8 on 2021-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('fee', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='admin_status',
        ),
        migrations.AlterField(
            model_name='staff',
            name='stype',
            field=models.CharField(blank=True, choices=[('1', 'Operations'), ('2', 'Sales'), ('3', 'Trainer'), ('4', 'Admin'), ('5', 'Operations Manager'), ('6', 'Sales Manager')], max_length=100, null=True),
        ),
    ]
