# Generated by Django 3.2.8 on 2021-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pic',
            field=models.ImageField(blank=True, default='images/couse.jpg', null=True, upload_to='images/course/'),
        ),
    ]
