# Generated by Django 3.2.8 on 2021-10-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_course_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('passcode', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('Weekend', 'Weekend'), ('Weekday', 'Weekday')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Yet to Start', 'Yet to Start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=100, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.course')),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'stype': '3'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.staff')),
            ],
        ),
    ]
