# Generated by Django 3.2.8 on 2021-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
