# Generated by Django 3.2.8 on 2021-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211007_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.ImageField(blank=True, default='course.jpg', null=True, upload_to='images/course/'),
        ),
    ]
