# Generated by Django 3.2.8 on 2021-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_course_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
