# Generated by Django 3.2.8 on 2021-10-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_batch_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Yet to Start', 'Yet to Start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('Weekend', 'Weekend'), ('Weekday', 'Weekday')], max_length=100),
        ),
    ]
