# Generated by Django 3.2.8 on 2021-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211007_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('2', 'Yet to Start'), ('1', 'Ongoing'), ('3', 'Completed'), ('4', 'Cancelled')], default='4', max_length=100),
        ),
    ]
