# Generated by Django 3.2.8 on 2021-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('2', 'Yet to Start'), ('1', 'Ongoing'), ('3', 'Completed'), ('4', 'Cancelled')], default='2', max_length=100),
        ),
    ]
