# Generated by Django 3.2.8 on 2021-10-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211008_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='to_be_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_edit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_by', to='accounts.staff'),
        ),
    ]
