# Generated by Django 3.2.8 on 2021-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail'), ('Draft', 'Draft')], max_length=100, null=True),
        ),
    ]
