# Generated by Django 3.2.8 on 2021-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211008_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/static/images/user3.png', null=True, upload_to='images/dp/'),
        ),
    ]
