# Generated by Django 3.2.8 on 2021-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
