# Generated by Django 3.2.8 on 2021-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_staff_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
