# Generated by Django 3.2.8 on 2021-10-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In Pipeline', 'In Pipeline'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Not Interested', 'Not Interested')], default='New', max_length=100, null=True)),
                ('generator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.staff')),
            ],
        ),
    ]
