# Generated by Django 3.2.8 on 2021-10-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
