# Generated by Django 3.2.8 on 2021-10-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(blank=True, limit_choices_to=models.Q(('status', 'Ongoing'), ('status', 'Yet to start'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='accounts.batch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='accounts.student')),
            ],
        ),
    ]
