# Generated by Django 3.2.8 on 2021-10-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_job_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
