# Generated by Django 3.2.8 on 2021-10-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_approvalcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='approval',
            field=models.BooleanField(blank=True, choices=[('1', 'Approved'), ('3', 'Rejected'), ('2', 'Pending')], default='2', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='approval',
            field=models.CharField(blank=True, choices=[('1', 'Approved'), ('3', 'Rejected'), ('2', 'Pending')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TempBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('passcode', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('Weekend', 'Weekend'), ('Weekday', 'Weekday')], max_length=100)),
                ('status', models.CharField(choices=[('2', 'Yet to Start'), ('1', 'Ongoing'), ('3', 'Completed'), ('4', 'Cancelled')], default='2', max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.course')),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'stype': '3'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.staff')),
            ],
        ),
    ]
