# Generated by Django 3.2.8 on 2021-10-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20211011_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbatch',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.batch'),
        ),
    ]
