# Generated by Django 3.2.8 on 2021-10-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_tempbatch_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='approval',
            field=models.CharField(blank=True, choices=[('1', 'Approved'), ('3', 'Rejected'), ('2', 'Pending')], default='2', max_length=100, null=True),
        ),
    ]
