# Generated by Django 3.2.8 on 2021-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20211012_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pic',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
