# Generated by Django 3.2.8 on 2021-10-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_tempbatch_to_be_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('stype', '4'), ('status', '5'), ('status', '6'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='accounts.staff'),
        ),
    ]
