# Generated by Django 3.2.8 on 2021-10-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_payments', to='accounts.student')),
            ],
        ),
        migrations.AlterField(
            model_name='reporting',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('stype', '4'), ('stype', '5'), ('stype', '6'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='stype',
            field=models.CharField(blank=True, choices=[('1', 'Operations'), ('2', 'Sales'), ('3', 'Trainer'), ('4', 'Admin'), ('5', 'Operations Manager'), ('6', 'Sales Manager'), ('7', 'Trainer Manager')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StudentPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('spd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_payment', to='accounts.studentpaymentdata')),
            ],
        ),
    ]
