# Generated by Django 3.2.8 on 2021-10-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20211013_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpayments',
            old_name='date',
            new_name='timestamp',
        ),
    ]
