# Generated by Django 3.2.8 on 2021-10-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_rename_date_studentpayments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayments',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.staff'),
        ),
    ]
