# Generated by Django 3.2.8 on 2021-10-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_studentpayments_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='approval',
            field=models.CharField(blank=True, choices=[('1', 'Approved'), ('3', 'Rejected'), ('2', 'Pending')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='to_be_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representative', to='accounts.staff'),
        ),
    ]
