# Generated by Django 3.2.8 on 2021-10-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20211016_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('1', 'Read'), ('2', 'Unread')], default='Unread', max_length=100),
        ),
    ]
