# Generated by Django 3.2.8 on 2021-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('1', 'Read'), ('2', 'Unread')], default='2', max_length=100),
        ),
    ]
