# Generated by Django 3.2.8 on 2021-10-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_webinar_cover_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_cover', models.ImageField(blank=True, default='accounts/static/images/webinar_cover.jpg', null=True, upload_to='')),
            ],
        ),
    ]
