# Generated by Django 3.2.8 on 2021-10-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20211017_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='images/assignment/')),
                ('date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, limit_choices_to={'status': 'Ongoing'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
            ],
        ),
    ]
