# Generated by Django 3.2.8 on 2021-10-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
