# Generated by Django 3.2.8 on 2021-10-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='images/project/'),
        ),
    ]
