# Generated by Django 3.2.8 on 2021-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_studentassignmentdata_studentprojectdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentdata',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprojectdata',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], max_length=100, null=True),
        ),
    ]
