# Generated by Django 3.2.8 on 2021-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursedata',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
