# Generated by Django 3.2.8 on 2021-10-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('stype', '4'), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_for', to='accounts.staff'),
        ),
    ]
