# Generated by Django 3.2.8 on 2021-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_chatquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
