# Generated by Django 3.2.8 on 2021-10-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20211021_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='student_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user_1_timestamp',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user_2_timestamp',
        ),
    ]
