# Generated by Django 3.2.8 on 2021-10-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20211021_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
