# Generated by Django 3.2.8 on 2021-10-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_auto_20211021_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='images/cv/'),
        ),
    ]
