# Generated by Django 3.2.8 on 2021-10-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0093_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateField(blank=True, null=True)),
                ('created_at', models.TimeField(blank=True, null=True)),
                ('modified_on', models.DateField(blank=True, null=True)),
                ('modified_at', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
