# Generated by Django 3.2.8 on 2021-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='images/notes/'),
        ),
    ]
