# Generated by Django 3.2.8 on 2021-10-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_alter_notes_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpics',
            name='bill',
            field=models.ImageField(blank=True, default='accounts/static/images/bill.jpg', null=True, upload_to=''),
        ),
    ]
