# Generated by Django 3.2.8 on 2021-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_defaultpics_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayments',
            name='bill_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
