# Generated by Django 3.2.8 on 2021-10-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_lead_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('stype', '2'), ('stype', '6'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='accounts.staff'),
        ),
    ]
