# Generated by Django 3.2.8 on 2021-10-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_auto_20211030_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
