# Generated by Django 3.2.8 on 2021-10-31 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_complaint_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
    ]
