# Generated by Django 3.2.8 on 2021-10-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_complaint_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Awaiting Support', 'Awaiting Support'), ('Awaiting Customer', 'Awaiting Customer'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
    ]
