# Generated by Django 3.2.8 on 2021-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='images/complaints'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images/complaints'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images/complaints'),
        ),
        migrations.AlterField(
            model_name='complaintcomment',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='images/complaints'),
        ),
        migrations.AlterField(
            model_name='complaintcomment',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images/complaints'),
        ),
        migrations.AlterField(
            model_name='complaintcomment',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images/complaints'),
        ),
    ]
