# Generated by Django 3.2.8 on 2021-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_auto_20211031_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
