# Generated by Django 3.2.8 on 2021-11-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_complaintcomment_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='images/notes/')),
                ('date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
            ],
        ),
        migrations.DeleteModel(
            name='ApprovalCount',
        ),
    ]
