# Generated by Django 3.2.8 on 2021-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_auto_20211102_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchnotes',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
