# Generated by Django 3.2.8 on 2021-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_studentsubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batches_attended',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
