# Generated by Django 3.2.8 on 2021-11-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
